### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by ttz0523** [Zhaozixiang1228/MMIF-CDDFuse#2]
This article is well written, but where is your code?

**Comment by Zhaozixiang1228** [comment]
Thanks for the concern. I just finished the camera-ready submission and the code will be open source this month.

**Comment by Zhaozixiang1228** [comment]
code released.

**Comment by ttz0523** [comment]
3Q very much:)
&nbsp;


语风不修仙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月4日(星期四) 下午5:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Zhaozixiang1228/MMIF-CDDFuse] Code? (Issue #2)





 
code released.
