### ISSUE TITLE
医学图像融合训练数据集

### ISSUE THREAD

**Issue by wangqh1996** [Zhaozixiang1228/MMIF-CDDFuse#21]
您好，非常感谢您的工作。我想知道具体在http://www.med.harvard.edu/AANLIB/home.html网站上获取得到的训练数据集是什么样的，能否给出更加详细的说明或者下载链接，现在只有测试集，谢谢！

**Comment by hexiao-cs** [comment]
Do you have access to a dataset for training medical images?
