### ISSUE TITLE
关于CNN Encoder的输入特征维度

### ISSUE THREAD

**Issue by Liujian1997** [Zhaozixiang1228/MMIF-CDDFuse#6]
您好！

经过Restormer后的特征图应该是（B，H*W，dim），想问一下是通过transpose(1, 2).reshape(B, dim, H, W)变成与CNN相似的特征图然后输入到CNN Encoder中吗？

**Comment by Zhaozixiang1228** [comment]
The dim of feature output by Restormer is B,C,H,W.
